services:
  fastapi:
    image: fastapi
    container_name: fastapi_app
    ports:
    - "8000:8000"
    build:
      context: ./fastapi_app
      dockerfile: dockerfile

  telegram_bot:
    image: bot
    container_name: bot_app
    build:
      context: ./tg_bot
      dockerfile: dockerfile
    depends_on:
      - fastapi
