FROM python:3.10.6-slim
WORKDIR /app
COPY requirements.txt requirements.txt
COPY . .
RUN apt update
RUN apt install postgresql-dev gcc python3-dev musl-dev
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --no-cache-dir -r requirements.txt
EXPOSE 8080

CMD ["uvicorn", "app:api", "--host", "0.0.0.0"]